package cli

type pluginInitTemplateDescriptor struct {
	path     string
	template string
}

var operationPluginInitTemplates = []pluginInitTemplateDescriptor{
	{path: ".github/workflows/release.yml", template: releaseWorkflowTemplate},
	{path: "AGENTS.md", template: agentsTemplate},
	{path: "Makefile", template: makefileTemplate},
	{path: "README.md", template: readmeTemplate},
	{path: "examples/demo.yaml", template: demoWorkflowTemplate},
	{path: "go.mod", template: goModTemplate},
	{path: "main.go", template: mainGoTemplate},
	{path: "main_test.go", template: mainTestGoTemplate},
	{path: "plugin.yaml", template: pluginYAMLTemplate},
}

const agentsTemplate = `# Agent Instructions

These instructions are for coding agents working inside this AWF plugin repository. They are operational constraints, not human onboarding text.

## Required AWF Knowledge

- Before changing plugin behavior, load and use the ` + "`awf-knowledge`" + ` skill.
- If ` + "`awf-knowledge`" + ` is not available in the active agent client, install or enable the AWF marketplace from ` + "`https://github.com/awf-project/awf-marketplace`" + `, then reload available skills before continuing.
- Do not invent AWF plugin SDK APIs from memory. Use ` + "`awf-knowledge`" + ` and the local ` + "`github.com/awf-project/cli/pkg/plugin/sdk`" + ` package as the source of truth.

## Current Scaffold Contract

- This repository is an AWF operation plugin scaffold generated by ` + "`awf plugin init --kind operation`" + `.
- The runtime plugin id is ` + "`{{.RuntimeID}}`" + `. Keep ` + "`plugin.yaml`" + ` ` + "`name`" + `, ` + "`sdk.BasePlugin.PluginName`" + `, generated examples, tests, and README references synchronized with that id.
- The generated distribution name is ` + "`{{.DistributionName}}`" + `. Keep package names, release archive names, local install paths, and checksum targets synchronized with that distribution name.
- The only implemented manifest capability in this scaffold is ` + "`operations`" + `. Do not add validators, custom step types, event listeners, or mixed capabilities unless the implementation, manifest, examples, tests, and release packaging are all updated in the same change.
- Operation identifiers are addressed from workflows as ` + "`{{.RuntimeID}}.<operation>`" + ` with state type ` + "`operation`" + `.

## Implementation Rules

- Keep ` + "`main.go`" + ` as the plugin entrypoint and call ` + "`sdk.Serve(newPlugin())`" + ` from ` + "`main`" + `.
- Implement each runtime operation through ` + "`OperationProvider`" + ` and describe it through ` + "`OperationSchemaProvider`" + `.
- Every operation must validate required inputs before doing work. Return ` + "`sdk.NewErrorResult`" + ` for invalid user input and ` + "`sdk.NewSuccessResult`" + ` for successful work.
- No operation may be a no-op. A successful operation must either produce a meaningful textual output, structured output fields, or an intentional external side effect covered by tests.
- Keep operation schema metadata complete enough for agents and ` + "`awf plugin list --operations`" + ` to discover required inputs, optional inputs, and structured outputs.
- When adding, renaming, or removing an operation, update ` + "`main.go`" + `, ` + "`main_test.go`" + `, ` + "`plugin.yaml`" + ` if capabilities change, ` + "`examples/demo.yaml`" + `, and ` + "`README.md`" + ` together.

## Workflow And Manifest Rules

- Keep workflow examples valid AWF YAML. Use ` + "`type: operation`" + ` and ` + "`operation: {{.RuntimeID}}.<operation>`" + ` for operation calls.
- Keep ` + "`plugin.yaml`" + ` semver-compatible: ` + "`version`" + ` must be semantic, ` + "`awf_version`" + ` must express the supported AWF range, and ` + "`capabilities`" + ` must match implemented runtime behavior.
- Do not expose secrets through default config values, example workflows, test fixtures, operation outputs, or logs.
- Keep generated release artifacts installable by AWF: binary, ` + "`plugin.yaml`" + `, archive name, and SHA-256 checksum data must stay aligned.

## Verification Gate

Run the narrowest relevant commands before finishing a change:

` + "```bash" + `
make test
make lint
make build
` + "```" + `

For runtime verification after behavior changes:

` + "```bash" + `
make install-local
awf plugin enable {{.DistributionName}}
awf plugin list --operations
awf run examples/demo.yaml
` + "```" + `

If any command cannot run in the current environment, report the exact command and the blocking condition.
`

const goModTemplate = `module {{.DistributionName}}

go 1.25.8

require (
	github.com/awf-project/cli {{.AWFModuleVersion}}
	github.com/stretchr/testify v1.11.1
)

{{- if .HasLocalAWFModule }}

replace github.com/awf-project/cli => {{.LocalAWFModulePath}}
{{- end }}
`

const mainGoTemplate = `package main

import (
	"context"
	"fmt"

	"github.com/awf-project/cli/pkg/plugin/sdk"
)

const (
	operationEcho = "echo"
	pluginVersion = "0.1.0"
)

type echoPlugin struct {
	sdk.BasePlugin
}

func newPlugin() *echoPlugin {
	return &echoPlugin{
		BasePlugin: sdk.BasePlugin{
			PluginName:    "{{.RuntimeID}}",
			PluginVersion: pluginVersion,
		},
	}
}

func (p *echoPlugin) Operations() []string {
	return []string{operationEcho}
}

func (p *echoPlugin) HandleOperation(_ context.Context, name string, inputs map[string]any) (*sdk.OperationResult, error) {
	if name != operationEcho {
		return sdk.NewErrorResult(fmt.Sprintf("unknown operation %q", name)), nil
	}

	text, ok := sdk.GetString(inputs, "text")
	if !ok || text == "" {
		return sdk.NewErrorResult("text is required"), nil
	}

	prefix, _ := sdk.GetString(inputs, "prefix")
	output := text
	if prefix != "" {
		output = prefix + text
	}

	return sdk.NewSuccessResult(output, map[string]any{
		"output": output,
		"text":   text,
		"prefix": prefix,
	}), nil
}

func (p *echoPlugin) GetOperationSchema(name string) (sdk.OperationMeta, bool) {
	if name != operationEcho {
		return sdk.OperationMeta{}, false
	}

	return sdk.OperationMeta{
		Description: "Echo text, optionally prepending a prefix.",
		Inputs: []sdk.InputMeta{
			{
				Name:        "text",
				Type:        sdk.InputTypeString,
				Required:    true,
				Description: "Text to echo.",
			},
			{
				Name:        "prefix",
				Type:        sdk.InputTypeString,
				Required:    false,
				Description: "Optional prefix prepended to the text.",
			},
		},
		Outputs: []sdk.OutputMeta{
			{Name: "output", Type: sdk.InputTypeString, Description: "Final echoed output."},
			{Name: "text", Type: sdk.InputTypeString, Description: "Original text input."},
			{Name: "prefix", Type: sdk.InputTypeString, Description: "Prefix input, when provided."},
		},
	}, true
}

func main() {
	sdk.Serve(newPlugin())
}
`

const mainTestGoTemplate = `package main

import (
	"context"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestEchoOperationSuccess(t *testing.T) {
	result, err := newPlugin().HandleOperation(context.Background(), "echo", map[string]any{"text": "hello"})

	require.NoError(t, err)
	require.True(t, result.Success)
	assert.Equal(t, "hello", result.Output)
	assert.Equal(t, map[string]any{"output": "hello", "text": "hello", "prefix": ""}, result.Data)
}

func TestEchoOperationPrefix(t *testing.T) {
	result, err := newPlugin().HandleOperation(context.Background(), "echo", map[string]any{
		"text":   "hello",
		"prefix": "say: ",
	})

	require.NoError(t, err)
	require.True(t, result.Success)
	assert.Equal(t, "say: hello", result.Output)
	assert.Equal(t, "say: ", result.Data["prefix"])
}

func TestEchoOperationMissingText(t *testing.T) {
	result, err := newPlugin().HandleOperation(context.Background(), "echo", map[string]any{})

	require.NoError(t, err)
	require.False(t, result.Success)
	assert.Contains(t, result.Error, "text")
}

func TestEchoOperationEmptyText(t *testing.T) {
	result, err := newPlugin().HandleOperation(context.Background(), "echo", map[string]any{"text": ""})

	require.NoError(t, err)
	require.False(t, result.Success)
	assert.Contains(t, result.Error, "text")
}

func TestEchoOperationUnknownOperation(t *testing.T) {
	result, err := newPlugin().HandleOperation(context.Background(), "missing", map[string]any{"text": "hello"})

	require.NoError(t, err)
	require.False(t, result.Success)
	assert.Contains(t, result.Error, "unknown operation")
}

func TestEchoOperationSchemaMetadata(t *testing.T) {
	schema, ok := newPlugin().GetOperationSchema("echo")

	require.True(t, ok)
	assert.Contains(t, schema.Description, "Echo")
	require.Len(t, schema.Inputs, 2)
	assert.Equal(t, "text", schema.Inputs[0].Name)
	assert.True(t, schema.Inputs[0].Required)
	assert.Equal(t, "prefix", schema.Inputs[1].Name)
	assert.False(t, schema.Inputs[1].Required)
	assert.ElementsMatch(t, []string{"output", "text", "prefix"}, []string{
		schema.Outputs[0].Name,
		schema.Outputs[1].Name,
		schema.Outputs[2].Name,
	})
}

func TestManifestValidation(t *testing.T) {
	content, err := os.ReadFile("plugin.yaml")
	require.NoError(t, err)

	var manifest map[string]any
	require.NoError(t, yaml.Unmarshal(content, &manifest))
	capabilities, ok := manifest["capabilities"].([]any)
	require.True(t, ok)
	require.NotEmpty(t, manifest["name"])
	require.NotEmpty(t, manifest["version"])
	require.NotEmpty(t, manifest["awf_version"])
	assert.Equal(t, "{{.RuntimeID}}", manifest["name"])
	assert.Equal(t, "0.1.0", manifest["version"])
	assert.Contains(t, capabilities, "operations")
}
`

const pluginYAMLTemplate = `name: {{.RuntimeID}}
version: 0.1.0
description: Echo operation plugin generated by awf plugin init.
awf_version: ">=0.6.0"
author: AWF Plugin Author
license: MIT
capabilities:
  - operations
`

const makefileTemplate = `.PHONY: build test lint install-local uninstall-local package checksums

PLUGIN_NAME := {{.Release.BinaryName}}
VERSION := {{.Release.Version}}
GOOS ?= $(shell go env GOOS)
GOARCH ?= $(shell go env GOARCH)
DIST_DIR := dist
PACKAGE_DIR := {{.Release.PackageDir}}
ARCHIVE := {{.Release.ArchiveName}}
GOFLAGS ?= -mod=mod

build:
	mkdir -p "$(DIST_DIR)"
	go build $(GOFLAGS) -o $(DIST_DIR)/$(PLUGIN_NAME) .

test:
	go test $(GOFLAGS) .

lint:
	go vet $(GOFLAGS) .

install-local: build
	mkdir -p "$${HOME}/.local/share/awf/plugins/{{.RuntimeID}}"
	cp "$(DIST_DIR)/$(PLUGIN_NAME)" "$${HOME}/.local/share/awf/plugins/{{.RuntimeID}}/$(PLUGIN_NAME)"
	cp plugin.yaml "$${HOME}/.local/share/awf/plugins/{{.RuntimeID}}/plugin.yaml"

uninstall-local:
	rm -rf "$${HOME}/.local/share/awf/plugins/{{.RuntimeID}}"

package: build
	rm -rf "$(DIST_DIR)/$(PACKAGE_DIR)"
	mkdir -p "$(DIST_DIR)/$(PACKAGE_DIR)"
	cp "$(DIST_DIR)/$(PLUGIN_NAME)" {{.Release.ManifestName}} "$(DIST_DIR)/$(PACKAGE_DIR)/"
	tar -C "$(DIST_DIR)/$(PACKAGE_DIR)" -czf "$(DIST_DIR)/$(ARCHIVE)" .

checksums: package
	cd "$(DIST_DIR)" && sha256sum *.tar.gz > {{.Release.ChecksumFile}}
`

const demoWorkflowTemplate = `name: {{.RuntimeID}} demo
version: "1.0"

states:
  initial: echo

  echo:
    type: operation
    operation: {{.RuntimeID}}.echo
    inputs:
      text: "hello from {{.RuntimeID}}"
      prefix: "AWF: "
    on_success: done
    on_failure: failed

  done:
    type: terminal
    status: success

  failed:
    type: terminal
    status: failure
`

const readmeTemplate = `# {{.DistributionName}}

This is a first plugin scaffold generated by ` + "`awf plugin init`" + `. It provides one operation named ` + "`{{.RuntimeID}}.echo`" + ` and uses ` + "`pkg/plugin/sdk`" + ` as the supported Go authoring API.

## First Run

` + "```sh" + `
awf plugin init awf-plugin-example --kind operation
cd awf-plugin-example
make test
make build
make install-local
awf plugin enable {{.DistributionName}}
awf plugin list --operations
awf run examples/demo.yaml
` + "```" + `

## Manifest

` + "`plugin.yaml`" + ` declares the runtime plugin name, version, AWF version constraint, author, license, and capabilities. The manifest ` + "`name`" + ` is the runtime id, so workflows call ` + "`{{.RuntimeID}}.echo`" + ` even though the installable distribution is ` + "`{{.DistributionName}}`" + `.

Required fields:
- ` + "`name`" + `: manifest ` + "`name`" + ` is the runtime id used by workflows and operation routing.
- ` + "`version`" + `: semantic version such as ` + "`0.1.0`" + `; release tags should use the same version, usually prefixed with ` + "`v`" + `.
- ` + "`description`" + `: user-facing summary shown by plugin tooling.
- ` + "`awf_version`" + `: AWF version compatibility constraint, for example ` + "`>=0.6.0`" + `.
- ` + "`capabilities`" + `: supported capabilities advertised to AWF.

Optional fields include ` + "`author`" + `, ` + "`license`" + `, and config schema declarations. Config schema conventions should describe stable keys, types, defaults, and whether values are required so validation and MCP exposure can present useful metadata.

Supported capability for this scaffold is ` + "`operations`" + `. Common validation failures include missing required fields, non-semantic version values, incompatible AWF version compatibility constraints, unsupported capabilities, malformed config schema entries, and release artifacts without a checksum. Published releases should include the binary, ` + "`plugin.yaml`" + `, and SHA-256 checksum data.

## SDK

` + "`main.go`" + ` uses the AWF plugin sdk, embeds ` + "`sdk.BasePlugin`" + `, serves the plugin with ` + "`sdk.Serve`" + `, and exposes operation schema metadata through ` + "`sdk.OperationSchemaProvider`" + `. The scaffold implements ` + "`OperationProvider`" + ` for execution and ` + "`OperationSchemaProvider`" + ` for schema metadata.

Authoring APIs and expectations:
- ` + "`sdk.Serve`" + ` starts the plugin process and wires it to AWF.
- ` + "`sdk.BasePlugin`" + ` supplies plugin identity and default lifecycle methods.
- Lifecycle methods handle setup, health, and shutdown behavior.
- ` + "`OperationProvider`" + ` declares operation names and handles runtime calls.
- ` + "`OperationSchemaProvider`" + ` returns schema metadata for inputs and structured outputs.
- input helpers such as ` + "`sdk.GetString`" + ` keep operation input parsing predictable.
- ` + "`sdk.NewSuccessResult`" + ` returns successful output plus structured outputs.
- ` + "`sdk.NewErrorResult`" + ` returns operation-level validation or execution errors.
- compatibility expectations: keep operation names, input types, output keys, and manifest capabilities stable across compatible releases.

## Testing And Commands

Generated commands:

` + "```sh" + `
make build
make test
make lint
make install-local
make uninstall-local
make package
make checksums
` + "```" + `

The tests cover echo success, prefix behavior, missing text, empty text, unknown operations, schema metadata, and manifest validation.

## Local Install

Build and install locally, then enable, list, and run the plugin:

` + "```sh" + `
make install-local
awf plugin enable {{.DistributionName}}
awf plugin list --operations
awf run examples/demo.yaml
make uninstall-local
` + "```" + `

## Package, Checksum, And Release

Create an installer-compatible package and checksum:

` + "```sh" + `
make package
make checksums
` + "```" + `

The release workflow packages the binary plus ` + "`plugin.yaml`" + ` into ` + "`{{.DistributionName}}_0.1.0_<goos>_<goarch>.tar.gz`" + ` and publishes SHA-256 checksums.
`

const releaseWorkflowTemplate = `name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        env:
          GOOS: ${{ "{{" }} matrix.goos {{ "}}" }}
          GOARCH: ${{ "{{" }} matrix.goarch {{ "}}" }}
          GOFLAGS: -mod=mod
        run: |
          mkdir -p dist/{{.Release.PackageDir}}
          go build -o "dist/{{.Release.PackageDir}}/{{.Release.BinaryName}}" .
          cp {{.Release.ManifestName}} dist/{{.Release.PackageDir}}/{{.Release.ManifestName}}
          tar -C dist/{{.Release.PackageDir}} -czf "dist/{{.DistributionName}}_{{.Release.Version}}_${GOOS}_${GOARCH}.tar.gz" .
      - name: Checksums
        run: |
          cd dist
          sha256sum *.tar.gz > checksums.txt
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/checksums.txt
`
