// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity of a validation issue.
// SEVERITY_UNSPECIFIED (proto3 zero value) is treated as ERROR by the host.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_WARNING     Severity = 1
	Severity_SEVERITY_ERROR       Severity = 2
	Severity_SEVERITY_INFO        Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_WARNING",
		2: "SEVERITY_ERROR",
		3: "SEVERITY_INFO",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_WARNING":     1,
		"SEVERITY_ERROR":       2,
		"SEVERITY_INFO":        3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_proto_plugin_v1_plugin_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetInfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string][]byte      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *InitRequest) GetConfig() map[string][]byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

type ListOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsRequest) Reset() {
	*x = ListOperationsRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsRequest) ProtoMessage() {}

func (x *ListOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListOperationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

type ListOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*OperationSchema     `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsResponse) Reset() {
	*x = ListOperationsResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsResponse) ProtoMessage() {}

func (x *ListOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ListOperationsResponse) GetOperations() []*OperationSchema {
	if x != nil {
		return x.Operations
	}
	return nil
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *GetOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *OperationSchema       `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *GetOperationResponse) GetOperation() *OperationSchema {
	if x != nil {
		return x.Operation
	}
	return nil
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Inputs        map[string][]byte      `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ExecuteRequest) GetInputs() map[string][]byte {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Data          map[string][]byte      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteResponse) GetData() map[string][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OperationSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Inputs        []*InputSchema         `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*OutputSchema        `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationSchema) Reset() {
	*x = OperationSchema{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationSchema) ProtoMessage() {}

func (x *OperationSchema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationSchema.ProtoReflect.Descriptor instead.
func (*OperationSchema) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *OperationSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperationSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OperationSchema) GetInputs() []*InputSchema {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *OperationSchema) GetOutputs() []*OutputSchema {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type InputSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Default       string                 `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Validation    string                 `protobuf:"bytes,6,opt,name=validation,proto3" json:"validation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputSchema) Reset() {
	*x = InputSchema{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputSchema) ProtoMessage() {}

func (x *InputSchema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputSchema.ProtoReflect.Descriptor instead.
func (*InputSchema) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *InputSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputSchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InputSchema) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *InputSchema) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *InputSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InputSchema) GetValidation() string {
	if x != nil {
		return x.Validation
	}
	return ""
}

type OutputSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputSchema) Reset() {
	*x = OutputSchema{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputSchema) ProtoMessage() {}

func (x *OutputSchema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputSchema.ProtoReflect.Descriptor instead.
func (*OutputSchema) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *OutputSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutputSchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutputSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ValidationIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      Severity               `protobuf:"varint,1,opt,name=severity,proto3,enum=plugin.v1.Severity" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Step          string                 `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	Field         string                 `protobuf:"bytes,4,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationIssue) Reset() {
	*x = ValidationIssue{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationIssue) ProtoMessage() {}

func (x *ValidationIssue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationIssue.ProtoReflect.Descriptor instead.
func (*ValidationIssue) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *ValidationIssue) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *ValidationIssue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationIssue) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *ValidationIssue) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type ValidateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowJson  []byte                 `protobuf:"bytes,1,opt,name=workflow_json,json=workflowJson,proto3" json:"workflow_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateWorkflowRequest) Reset() {
	*x = ValidateWorkflowRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateWorkflowRequest) ProtoMessage() {}

func (x *ValidateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ValidateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateWorkflowRequest) GetWorkflowJson() []byte {
	if x != nil {
		return x.WorkflowJson
	}
	return nil
}

type ValidateWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*ValidationIssue     `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateWorkflowResponse) Reset() {
	*x = ValidateWorkflowResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateWorkflowResponse) ProtoMessage() {}

func (x *ValidateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*ValidateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateWorkflowResponse) GetIssues() []*ValidationIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type ValidateStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowJson  []byte                 `protobuf:"bytes,1,opt,name=workflow_json,json=workflowJson,proto3" json:"workflow_json,omitempty"`
	StepName      string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateStepRequest) Reset() {
	*x = ValidateStepRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStepRequest) ProtoMessage() {}

func (x *ValidateStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStepRequest.ProtoReflect.Descriptor instead.
func (*ValidateStepRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *ValidateStepRequest) GetWorkflowJson() []byte {
	if x != nil {
		return x.WorkflowJson
	}
	return nil
}

func (x *ValidateStepRequest) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

type ValidateStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*ValidationIssue     `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateStepResponse) Reset() {
	*x = ValidateStepResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStepResponse) ProtoMessage() {}

func (x *ValidateStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStepResponse.ProtoReflect.Descriptor instead.
func (*ValidateStepResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *ValidateStepResponse) GetIssues() []*ValidationIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type ListStepTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStepTypesRequest) Reset() {
	*x = ListStepTypesRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStepTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStepTypesRequest) ProtoMessage() {}

func (x *ListStepTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStepTypesRequest.ProtoReflect.Descriptor instead.
func (*ListStepTypesRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{20}
}

type StepTypeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepTypeInfo) Reset() {
	*x = StepTypeInfo{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepTypeInfo) ProtoMessage() {}

func (x *StepTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepTypeInfo.ProtoReflect.Descriptor instead.
func (*StepTypeInfo) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *StepTypeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepTypeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListStepTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepTypes     []*StepTypeInfo        `protobuf:"bytes,1,rep,name=step_types,json=stepTypes,proto3" json:"step_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStepTypesResponse) Reset() {
	*x = ListStepTypesResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStepTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStepTypesResponse) ProtoMessage() {}

func (x *ListStepTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStepTypesResponse.ProtoReflect.Descriptor instead.
func (*ListStepTypesResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *ListStepTypesResponse) GetStepTypes() []*StepTypeInfo {
	if x != nil {
		return x.StepTypes
	}
	return nil
}

type ExecuteStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepName      string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	StepType      string                 `protobuf:"bytes,2,opt,name=step_type,json=stepType,proto3" json:"step_type,omitempty"`
	Config        []byte                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Inputs        []byte                 `protobuf:"bytes,4,opt,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStepRequest) Reset() {
	*x = ExecuteStepRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStepRequest) ProtoMessage() {}

func (x *ExecuteStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStepRequest.ProtoReflect.Descriptor instead.
func (*ExecuteStepRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *ExecuteStepRequest) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *ExecuteStepRequest) GetStepType() string {
	if x != nil {
		return x.StepType
	}
	return ""
}

func (x *ExecuteStepRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ExecuteStepRequest) GetInputs() []byte {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type ExecuteStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStepResponse) Reset() {
	*x = ExecuteStepResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStepResponse) ProtoMessage() {}

func (x *ExecuteStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStepResponse.ProtoReflect.Descriptor instead.
func (*ExecuteStepResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *ExecuteStepResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteStepResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecuteStepResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_proto_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/plugin/v1/plugin.proto\x12\tplugin.v1\"\x10\n" +
	"\x0eGetInfoRequest\"\x85\x01\n" +
	"\x0fGetInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"\x84\x01\n" +
	"\vInitRequest\x12:\n" +
	"\x06config\x18\x01 \x03(\v2\".plugin.v1.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x0e\n" +
	"\fInitResponse\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\x17\n" +
	"\x15ListOperationsRequest\"T\n" +
	"\x16ListOperationsResponse\x12:\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x1a.plugin.v1.OperationSchemaR\n" +
	"operations\")\n" +
	"\x13GetOperationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"P\n" +
	"\x14GetOperationResponse\x128\n" +
	"\toperation\x18\x01 \x01(\v2\x1a.plugin.v1.OperationSchemaR\toperation\"\xa8\x01\n" +
	"\x0eExecuteRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12=\n" +
	"\x06inputs\x18\x02 \x03(\v2%.plugin.v1.ExecuteRequest.InputsEntryR\x06inputs\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xcc\x01\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x128\n" +
	"\x04data\x18\x03 \x03(\v2$.plugin.v1.ExecuteResponse.DataEntryR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xaa\x01\n" +
	"\x0fOperationSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12.\n" +
	"\x06inputs\x18\x03 \x03(\v2\x16.plugin.v1.InputSchemaR\x06inputs\x121\n" +
	"\aoutputs\x18\x04 \x03(\v2\x17.plugin.v1.OutputSchemaR\aoutputs\"\xad\x01\n" +
	"\vInputSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x18\n" +
	"\adefault\x18\x04 \x01(\tR\adefault\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"validation\x18\x06 \x01(\tR\n" +
	"validation\"X\n" +
	"\fOutputSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x86\x01\n" +
	"\x0fValidationIssue\x12/\n" +
	"\bseverity\x18\x01 \x01(\x0e2\x13.plugin.v1.SeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04step\x18\x03 \x01(\tR\x04step\x12\x14\n" +
	"\x05field\x18\x04 \x01(\tR\x05field\">\n" +
	"\x17ValidateWorkflowRequest\x12#\n" +
	"\rworkflow_json\x18\x01 \x01(\fR\fworkflowJson\"N\n" +
	"\x18ValidateWorkflowResponse\x122\n" +
	"\x06issues\x18\x01 \x03(\v2\x1a.plugin.v1.ValidationIssueR\x06issues\"W\n" +
	"\x13ValidateStepRequest\x12#\n" +
	"\rworkflow_json\x18\x01 \x01(\fR\fworkflowJson\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\"J\n" +
	"\x14ValidateStepResponse\x122\n" +
	"\x06issues\x18\x01 \x03(\v2\x1a.plugin.v1.ValidationIssueR\x06issues\"\x16\n" +
	"\x14ListStepTypesRequest\"D\n" +
	"\fStepTypeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"O\n" +
	"\x15ListStepTypesResponse\x126\n" +
	"\n" +
	"step_types\x18\x01 \x03(\v2\x17.plugin.v1.StepTypeInfoR\tstepTypes\"~\n" +
	"\x12ExecuteStepRequest\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12\x1b\n" +
	"\tstep_type\x18\x02 \x01(\tR\bstepType\x12\x16\n" +
	"\x06config\x18\x03 \x01(\fR\x06config\x12\x16\n" +
	"\x06inputs\x18\x04 \x01(\fR\x06inputs\"^\n" +
	"\x13ExecuteStepResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode*a\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x01\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x02\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x032\xcf\x01\n" +
	"\rPluginService\x12@\n" +
	"\aGetInfo\x12\x19.plugin.v1.GetInfoRequest\x1a\x1a.plugin.v1.GetInfoResponse\x127\n" +
	"\x04Init\x12\x16.plugin.v1.InitRequest\x1a\x17.plugin.v1.InitResponse\x12C\n" +
	"\bShutdown\x12\x1a.plugin.v1.ShutdownRequest\x1a\x1b.plugin.v1.ShutdownResponse2\xfc\x01\n" +
	"\x10OperationService\x12U\n" +
	"\x0eListOperations\x12 .plugin.v1.ListOperationsRequest\x1a!.plugin.v1.ListOperationsResponse\x12O\n" +
	"\fGetOperation\x12\x1e.plugin.v1.GetOperationRequest\x1a\x1f.plugin.v1.GetOperationResponse\x12@\n" +
	"\aExecute\x12\x19.plugin.v1.ExecuteRequest\x1a\x1a.plugin.v1.ExecuteResponse2\xc0\x01\n" +
	"\x10ValidatorService\x12[\n" +
	"\x10ValidateWorkflow\x12\".plugin.v1.ValidateWorkflowRequest\x1a#.plugin.v1.ValidateWorkflowResponse\x12O\n" +
	"\fValidateStep\x12\x1e.plugin.v1.ValidateStepRequest\x1a\x1f.plugin.v1.ValidateStepResponse2\xb3\x01\n" +
	"\x0fStepTypeService\x12R\n" +
	"\rListStepTypes\x12\x1f.plugin.v1.ListStepTypesRequest\x1a .plugin.v1.ListStepTypesResponse\x12L\n" +
	"\vExecuteStep\x12\x1d.plugin.v1.ExecuteStepRequest\x1a\x1e.plugin.v1.ExecuteStepResponseB5Z3github.com/awf-project/cli/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_proto_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_v1_plugin_proto_rawDescData []byte
)

func file_proto_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_v1_plugin_proto_rawDescData
}

var file_proto_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_plugin_v1_plugin_proto_goTypes = []any{
	(Severity)(0),                    // 0: plugin.v1.Severity
	(*GetInfoRequest)(nil),           // 1: plugin.v1.GetInfoRequest
	(*GetInfoResponse)(nil),          // 2: plugin.v1.GetInfoResponse
	(*InitRequest)(nil),              // 3: plugin.v1.InitRequest
	(*InitResponse)(nil),             // 4: plugin.v1.InitResponse
	(*ShutdownRequest)(nil),          // 5: plugin.v1.ShutdownRequest
	(*ShutdownResponse)(nil),         // 6: plugin.v1.ShutdownResponse
	(*ListOperationsRequest)(nil),    // 7: plugin.v1.ListOperationsRequest
	(*ListOperationsResponse)(nil),   // 8: plugin.v1.ListOperationsResponse
	(*GetOperationRequest)(nil),      // 9: plugin.v1.GetOperationRequest
	(*GetOperationResponse)(nil),     // 10: plugin.v1.GetOperationResponse
	(*ExecuteRequest)(nil),           // 11: plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil),          // 12: plugin.v1.ExecuteResponse
	(*OperationSchema)(nil),          // 13: plugin.v1.OperationSchema
	(*InputSchema)(nil),              // 14: plugin.v1.InputSchema
	(*OutputSchema)(nil),             // 15: plugin.v1.OutputSchema
	(*ValidationIssue)(nil),          // 16: plugin.v1.ValidationIssue
	(*ValidateWorkflowRequest)(nil),  // 17: plugin.v1.ValidateWorkflowRequest
	(*ValidateWorkflowResponse)(nil), // 18: plugin.v1.ValidateWorkflowResponse
	(*ValidateStepRequest)(nil),      // 19: plugin.v1.ValidateStepRequest
	(*ValidateStepResponse)(nil),     // 20: plugin.v1.ValidateStepResponse
	(*ListStepTypesRequest)(nil),     // 21: plugin.v1.ListStepTypesRequest
	(*StepTypeInfo)(nil),             // 22: plugin.v1.StepTypeInfo
	(*ListStepTypesResponse)(nil),    // 23: plugin.v1.ListStepTypesResponse
	(*ExecuteStepRequest)(nil),       // 24: plugin.v1.ExecuteStepRequest
	(*ExecuteStepResponse)(nil),      // 25: plugin.v1.ExecuteStepResponse
	nil,                              // 26: plugin.v1.InitRequest.ConfigEntry
	nil,                              // 27: plugin.v1.ExecuteRequest.InputsEntry
	nil,                              // 28: plugin.v1.ExecuteResponse.DataEntry
}
var file_proto_plugin_v1_plugin_proto_depIdxs = []int32{
	26, // 0: plugin.v1.InitRequest.config:type_name -> plugin.v1.InitRequest.ConfigEntry
	13, // 1: plugin.v1.ListOperationsResponse.operations:type_name -> plugin.v1.OperationSchema
	13, // 2: plugin.v1.GetOperationResponse.operation:type_name -> plugin.v1.OperationSchema
	27, // 3: plugin.v1.ExecuteRequest.inputs:type_name -> plugin.v1.ExecuteRequest.InputsEntry
	28, // 4: plugin.v1.ExecuteResponse.data:type_name -> plugin.v1.ExecuteResponse.DataEntry
	14, // 5: plugin.v1.OperationSchema.inputs:type_name -> plugin.v1.InputSchema
	15, // 6: plugin.v1.OperationSchema.outputs:type_name -> plugin.v1.OutputSchema
	0,  // 7: plugin.v1.ValidationIssue.severity:type_name -> plugin.v1.Severity
	16, // 8: plugin.v1.ValidateWorkflowResponse.issues:type_name -> plugin.v1.ValidationIssue
	16, // 9: plugin.v1.ValidateStepResponse.issues:type_name -> plugin.v1.ValidationIssue
	22, // 10: plugin.v1.ListStepTypesResponse.step_types:type_name -> plugin.v1.StepTypeInfo
	1,  // 11: plugin.v1.PluginService.GetInfo:input_type -> plugin.v1.GetInfoRequest
	3,  // 12: plugin.v1.PluginService.Init:input_type -> plugin.v1.InitRequest
	5,  // 13: plugin.v1.PluginService.Shutdown:input_type -> plugin.v1.ShutdownRequest
	7,  // 14: plugin.v1.OperationService.ListOperations:input_type -> plugin.v1.ListOperationsRequest
	9,  // 15: plugin.v1.OperationService.GetOperation:input_type -> plugin.v1.GetOperationRequest
	11, // 16: plugin.v1.OperationService.Execute:input_type -> plugin.v1.ExecuteRequest
	17, // 17: plugin.v1.ValidatorService.ValidateWorkflow:input_type -> plugin.v1.ValidateWorkflowRequest
	19, // 18: plugin.v1.ValidatorService.ValidateStep:input_type -> plugin.v1.ValidateStepRequest
	21, // 19: plugin.v1.StepTypeService.ListStepTypes:input_type -> plugin.v1.ListStepTypesRequest
	24, // 20: plugin.v1.StepTypeService.ExecuteStep:input_type -> plugin.v1.ExecuteStepRequest
	2,  // 21: plugin.v1.PluginService.GetInfo:output_type -> plugin.v1.GetInfoResponse
	4,  // 22: plugin.v1.PluginService.Init:output_type -> plugin.v1.InitResponse
	6,  // 23: plugin.v1.PluginService.Shutdown:output_type -> plugin.v1.ShutdownResponse
	8,  // 24: plugin.v1.OperationService.ListOperations:output_type -> plugin.v1.ListOperationsResponse
	10, // 25: plugin.v1.OperationService.GetOperation:output_type -> plugin.v1.GetOperationResponse
	12, // 26: plugin.v1.OperationService.Execute:output_type -> plugin.v1.ExecuteResponse
	18, // 27: plugin.v1.ValidatorService.ValidateWorkflow:output_type -> plugin.v1.ValidateWorkflowResponse
	20, // 28: plugin.v1.ValidatorService.ValidateStep:output_type -> plugin.v1.ValidateStepResponse
	23, // 29: plugin.v1.StepTypeService.ListStepTypes:output_type -> plugin.v1.ListStepTypesResponse
	25, // 30: plugin.v1.StepTypeService.ExecuteStep:output_type -> plugin.v1.ExecuteStepResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_plugin_v1_plugin_proto_init() }
func file_proto_plugin_v1_plugin_proto_init() {
	if File_proto_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_proto_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_proto_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_v1_plugin_proto = out.File
	file_proto_plugin_v1_plugin_proto_goTypes = nil
	file_proto_plugin_v1_plugin_proto_depIdxs = nil
}
